### ISSUE TITLE
add dependencies.

### ISSUE THREAD

**Issue by YoushaaMurhij** [georgeliu233/STrajNet#4]
Thanks for sharing your code!
Would you please describe your environment (TF, Waymo-open-dataset and python versions)?

**Comment by YoushaaMurhij** [comment]
I have another question. I think, it is related to TF Version:
I am facing this error while launching train.py:

```bash
epoch 1/15
2023-01-23 19:38:59.136886: W tensorflow/core/framework/dataset.cc:768] Input of GeneratorDatasetOp::Dataset will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
2023-01-23 19:39:09.307530: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:390] Filling up shuffle buffer (this may take a while): 18 of 64
2023-01-23 19:39:19.261657: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:390] Filling up shuffle buffer (this may take a while): 37 of 64
2023-01-23 19:39:29.635397: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:390] Filling up shuffle buffer (this may take a while): 55 of 64
2023-01-23 19:39:35.340840: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:415] Shuffle buffer filled.
      4/Unknown - 107s 27s/sample - obs_loss: 0.0000e+00 - occ_loss: 0.0000e+00 - flow_loss: 0.0000e+00 - warp_loss: 0.0000e+00Traceback (most recent call last):
  File "train.py", line 392, in <module>
    model_training(train_dataset, valid_dataset, EPOCH,continue_ep)
  File "train.py", line 319, in model_training
    outputs = strategy.run(train_step,args=(batch,))
  File "/home/user/.local/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1312, in run
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2888, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 676, in _call_for_each_replica
    return mirrored_run.call_for_each_replica(
  File "/home/user/.local/lib/python3.8/site-packages/tensorflow/python/distribute/mirrored_run.py", line 82, in call_for_each_replica
    return wrapped(args, kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/user/.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'interpolate_bilinear/gather-bottom_left/GatherV2' defined at (most recent call last):
    File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "train.py", line 220, in train_step
      loss_dict = loss_fn(true_waypoints=true_waypoints,pred_waypoint_logits=logits,curr_ogm=ogm[:,:,:,-1,0])
    File "/home/user/STrajNet/loss.py", line 100, in __call__
      for k in range(n_waypoints):
    File "/home/user/STrajNet/loss.py", line 127, in __call__
      if self.use_gt:
    File "/home/user/STrajNet/loss.py", line 129, in __call__
      wp_org = sample(
    File "/home/user/STrajNet/occu_metric.py", line 406, in sample
      flat_sampled = interpolate_bilinear(
    File "/home/user/STrajNet/tfa_image.py", line 49, in interpolate_bilinear
      return _interpolate_bilinear_with_checks(grid, query_points, indexing, name)
    File "/home/user/STrajNet/tfa_image.py", line 84, in _interpolate_bilinear_with_checks
      return _interpolate_bilinear_impl(grid, query_points, indexing, name)
    File "/home/user/STrajNet/tfa_image.py", line 164, in _interpolate_bilinear_impl
      bottom_left = gather(ceils[0], floors[1], "bottom_left")
    File "/home/user/STrajNet/tfa_image.py", line 158, in gather
      gathered_values = tf.gather(flattened_grid, linear_coordinates)
Node: 'interpolate_bilinear/gather-bottom_left/GatherV2'
indices[1,54617] = -2147416826 is not in [0, 266256)
         [[{{node interpolate_bilinear/gather-bottom_left/GatherV2}}]] [Op:__inference_train_step_117670]

```
Any suggestions? 
Thanks!

**Comment by YoushaaMurhij** [comment]
TF2.6 +WOD-tf-2-6-0 worked!
